apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
        - name: sampleapp-container
          image: 273354669111.dkr.ecr.ap-south-1.amazonaws.com/sampleapp:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: sampleapp-dev
  namespace: dev
spec:
  selector:
    app: sampleapp-dev  
  ports:
    - protocol: TCP      
      port: 80             
      targetPort: 8081     
  type: ClusterIP          

