name: sampleapp-prod
namespace: prod
replicaCount: 1
image:
  repository: 273354669111.dkr.ecr.ap-south-1.amazonaws.com/sampleapp
  tag: "1.1.1"
containerPort: 8083
service:
  name: sampleapp-prod
  port: 8083
serviceAccount:
  create: true
  name: sampleapp-serviceaccount
ingress:
  enabled: false
autoscaling:
  enabled: false 