name: sampleapp-dev
namespace: dev
replicaCount: 1
image:
  repository: 273354669111.dkr.ecr.ap-south-1.amazonaws.com/sampleapp
  tag: "1.0.0"
containerPort: 8081
service:
  name: sampleapp-dev
  port: 8081